Hec reverify resent email
hmrc/hec-applicant-frontend pull request #114
Opened 2022-01-07 14:49 UTC by priyankadhiman3006

2022-01-07 15:04 UTC, nubz requested changes

2022-01-07 15:04 UTC, nubz commented on app/uk/gov/hmrc/hecapplicantfrontend/views/VerifyResentPasscode.scala.html
> +    <p class="govuk-label--m">
this is not a label and should not use a label css class - this is a heading and should be an `<h2>` element using `govuk-heading-m` css class instead of a `<p>` element

2022-01-07 15:04 UTC, nubz commented on app/uk/gov/hmrc/hecapplicantfrontend/views/VerifyResentPasscode.scala.html
> +    @messages(s"$key.p2", email.value)
this should be using a new message instead of `s"$key.p2"` - the new message content should be `A new email confirmation code has been sent to {0}. Enter this confirmation code below.`

2022-01-07 15:07 UTC, AndyHWChung commented on app/uk/gov/hmrc/hecapplicantfrontend/controllers/VerifyResentEmailPasscodeController.scala
> +      val session = request.sessionData
a lot of stuff in this controller is pretty much exactly the same as what's in the `VerifyEmailPasscodeController` - it might be worth having these endpoints all in the same controller and reusing the logic between them

2022-01-10 11:32 UTC, priyankadhiman3006 commented on app/uk/gov/hmrc/hecapplicantfrontend/controllers/VerifyResentEmailPasscodeController.scala
> +      val session = request.sessionData
[updated](https://github.com/hmrc/hec-applicant-frontend/commit/72693ae3931a5df8deed62d6d2e6f08613709f3c)

2022-01-10 11:32 UTC, priyankadhiman3006 commented on app/uk/gov/hmrc/hecapplicantfrontend/views/VerifyResentPasscode.scala.html
> +    <p class="govuk-label--m">
[updated](https://github.com/hmrc/hec-applicant-frontend/commit/72693ae3931a5df8deed62d6d2e6f08613709f3c)

2022-01-10 11:32 UTC, priyankadhiman3006 commented on app/uk/gov/hmrc/hecapplicantfrontend/views/VerifyResentPasscode.scala.html
> +    @messages(s"$key.p2", email.value)
[updated](https://github.com/hmrc/hec-applicant-frontend/commit/72693ae3931a5df8deed62d6d2e6f08613709f3c)

2022-01-10 11:38 UTC, AndyHWChung commented on app/uk/gov/hmrc/hecapplicantfrontend/controllers/VerifyEmailPasscodeController.scala
> +//  def handleValidPasscode(
this can be cleaned up

2022-01-10 11:38 UTC, nubz commented on app/uk/gov/hmrc/hecapplicantfrontend/views/VerifyResentPasscode.scala.html
> +    <p class="govuk-label--m">
this hasn't actually changed in these updates by the looks of it, it is still a paragraph using a label class instead of `<h2 class="govuk-heading-m">`

2022-01-10 11:50 UTC, priyankadhiman3006 commented on app/uk/gov/hmrc/hecapplicantfrontend/views/VerifyResentPasscode.scala.html
> +    <p class="govuk-label--m">
let me double check

2022-01-10 11:52 UTC, priyankadhiman3006 commented on app/uk/gov/hmrc/hecapplicantfrontend/views/VerifyResentPasscode.scala.html
> +    <p class="govuk-label--m">
i think this got change when i did rebase  🤦‍♀️ . let me fix this

2022-01-10 12:00 UTC, priyankadhiman3006 commented on app/uk/gov/hmrc/hecapplicantfrontend/views/VerifyResentPasscode.scala.html
> +    <p class="govuk-label--m">
[updated now](https://github.com/hmrc/hec-applicant-frontend/pull/114/commits/5e414678b59c3e1c34931019706f31593c16b371)

2022-01-10 12:00 UTC, priyankadhiman3006 commented on app/uk/gov/hmrc/hecapplicantfrontend/controllers/VerifyEmailPasscodeController.scala
> +//  def handleValidPasscode(
[updated](https://github.com/hmrc/hec-applicant-frontend/pull/114/commits/5e414678b59c3e1c34931019706f31593c16b371)

2022-01-10 12:11 UTC, AndyHWChung commented on app/uk/gov/hmrc/hecapplicantfrontend/views/VerifyResentPasscode.scala.html
> +    @messages(s"$key.label1")
`$key.h2` would make more sense if this is not a label

2022-01-10 12:19 UTC, priyankadhiman3006 commented on app/uk/gov/hmrc/hecapplicantfrontend/views/VerifyResentPasscode.scala.html
> +    @messages(s"$key.label1")
done

2022-01-10 13:42 UTC, nubz approved these changes

2022-01-10 14:26 UTC, merged